import { asset } from "@/lib/asset";

/**
 * Photo registry. Every file is generated by scripts/build-photos.py from
 * Jake's own uploads. Captions name the car and nothing else: no photo here is
 * tied to a specific service, so none should be captioned as one.
 *
 * Cuts per photo (see the script):
 *   w = 4:3 landscape at 640 and 1280
 *   t = 4:5 portrait at 480, 750 and 960
 *   f = full frame at 720, 1080 and 1600 (working shots only)
 */
export interface Car {
  slug: string;
  name: string; // caption
  alt: string;
}

export const CARS: Car[] = [
  { slug: "huracan", name: "Lamborghini Huracán", alt: "A matte blue Lamborghini Huracán on a driveway" },
  { slug: "audi-r8", name: "Audi R8", alt: "A yellow Audi R8 on a driveway" },
  { slug: "granturismo", name: "Maserati GranTurismo", alt: "A white Maserati GranTurismo on a driveway" },
  { slug: "cybertruck", name: "Tesla Cybertruck", alt: "A Tesla Cybertruck on a driveway" },
  { slug: "bmw-m4", name: "BMW M4", alt: "A white BMW M4 on a wet driveway" },
  { slug: "corvette-c5", name: "Chevrolet Corvette C5", alt: "A red Chevrolet Corvette C5 on a brick driveway" },
  { slug: "defender", name: "Land Rover Defender", alt: "A white Land Rover Defender on a driveway" },
  { slug: "bmw-e46", name: "BMW E46 coupe", alt: "A grey BMW E46 coupe on a wet driveway" },
  { slug: "audi-rs3", name: "Audi RS 3", alt: "A white Audi RS 3 on a driveway" },
  { slug: "bmw-ix", name: "BMW iX", alt: "A dark red BMW iX on a driveway" },
  { slug: "range-rover-sport", name: "Range Rover Sport", alt: "A black Range Rover Sport on a driveway" },
  { slug: "acura-tlx", name: "Acura TLX", alt: "A white Acura TLX on a driveway" },
  { slug: "mercedes-glc", name: "Mercedes-Benz GLC", alt: "A silver Mercedes-Benz GLC on a driveway" },
  { slug: "jetta-gli", name: "Volkswagen Jetta GLI", alt: "A red Volkswagen Jetta GLI on a driveway" },
  { slug: "bmw-3-series", name: "BMW 3 Series", alt: "A blue BMW 3 Series on a driveway" },
  { slug: "discovery-sport", name: "Land Rover Discovery Sport", alt: "A dark blue Land Rover Discovery Sport on a driveway" },
  { slug: "audi-a5-cabriolet", name: "Audi A5 Cabriolet", alt: "A dark Audi A5 Cabriolet on a driveway" },
  { slug: "chevy-ck", name: "Chevrolet C/K pickup", alt: "A blue Chevrolet C/K pickup on a driveway" },
];

export const car = (slug: string): Car => {
  const found = CARS.find((c) => c.slug === slug);
  if (!found) throw new Error(`Unknown car photo: ${slug}`);
  return found;
};

/** The two professional photos carry the photographer's mark. Credit them. */
export const PHOTO_CREDIT = "@breckenmutch";

export const WORKING = {
  rinse: {
    slug: "jake-rinse-huracan",
    alt: "Jake rinsing snow foam off a blue Lamborghini Huracán on a tree-lined driveway",
  },
  dry: {
    slug: "jake-dry-huracan",
    alt: "Jake drying a blue Lamborghini Huracán with a towel",
  },
  wash: {
    slug: "jake-wash-rs3",
    alt: "Jake hand washing the hood of a white Audi RS 3 with a wash mitt",
  },
} as const;

type Cut = "w" | "t" | "f";
const WIDTHS: Record<Cut, number[]> = { w: [640, 1280], t: [480, 750, 960], f: [720, 1080, 1600] };
const RATIO: Record<Cut, number> = { w: 3 / 4, t: 5 / 4, f: 3 / 2 };
// Full frames that are not 2:3. The RS 3 shot is a very tall phone frame.
const FULL_RATIO: Record<string, number> = { "jake-wash-rs3": 2589 / 1197 };

/** src, srcSet and intrinsic size for one cut of one photo. */
export function photoSet(slug: string, cut: Cut) {
  const widths = WIDTHS[cut];
  const largest = widths[widths.length - 1];
  return {
    src: asset(`/photos/${slug}-${cut}${largest}.webp`),
    srcSet: widths.map((w) => `${asset(`/photos/${slug}-${cut}${w}.webp`)} ${w}w`).join(", "),
    avifSrcSet: widths.map((w) => `${asset(`/photos/${slug}-${cut}${w}.avif`)} ${w}w`).join(", "),
    width: largest,
    height: Math.round(largest * (cut === "f" ? (FULL_RATIO[slug] ?? RATIO.f) : RATIO[cut])),
  };
}
